# Generated by Django 5.0.2 on 2024-03-03 09:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("place_of_creation", models.CharField(max_length=100)),
                ("date_of_creation", models.DateField()),
                ("date_of_service", models.DateField()),
                ("invoice_number", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("PLN", "Polish Zloty (PLN)"),
                            ("EUR", "Euro (EUR)"),
                            ("GBP", "British Pound Sterling (GBP)"),
                            ("CHF", "Swiss Franc (CHF)"),
                            ("SEK", "Swedish Krona (SEK)"),
                            ("NOK", "Norwegian Krone (NOK)"),
                            ("DKK", "Danish Krone (DKK)"),
                            ("HUF", "Hungarian Forint (HUF)"),
                            ("CZK", "Czech Koruna (CZK)"),
                            ("RON", "Romanian Leu (RON)"),
                            ("USD", "US Dollar (USD)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "method_payment",
                    models.CharField(
                        choices=[
                            ("money transfer", "Money transfer"),
                            ("cash", "CASH"),
                        ],
                        max_length=20,
                    ),
                ),
                ("service_type_1", models.CharField(max_length=100)),
                ("service_type_2", models.CharField(blank=True, max_length=100)),
                ("service_type_3", models.CharField(blank=True, max_length=100)),
                (
                    "unit_1",
                    models.CharField(
                        choices=[
                            ("hours", "HOURS"),
                            ("days", "DAYS"),
                            ("quantity", "QUANTITY"),
                            ("units", "UNITS"),
                            ("pieces", "PIECES"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "unit_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hours", "HOURS"),
                            ("days", "DAYS"),
                            ("quantity", "QUANTITY"),
                            ("units", "UNITS"),
                            ("pieces", "PIECES"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "unit_3",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hours", "HOURS"),
                            ("days", "DAYS"),
                            ("quantity", "QUANTITY"),
                            ("units", "UNITS"),
                            ("pieces", "PIECES"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "price_1",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=100,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=100,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=100,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount_1",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount_2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount_3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("total_price_1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price_2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price_3", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("company_name", models.CharField(max_length=255)),
                ("company_street_address", models.CharField(max_length=255)),
                ("company_city", models.CharField(max_length=100)),
                ("company_zip_code", models.CharField(max_length=50)),
                ("company_tax_id", models.CharField(max_length=100)),
                ("company_phone", models.CharField(max_length=20)),
                ("company_account_number", models.CharField(blank=True, max_length=50)),
                ("customer_company_name", models.CharField(max_length=255)),
                ("customer_street_address", models.CharField(max_length=255)),
                ("customer_city", models.CharField(max_length=100)),
                ("customer_zip_code", models.CharField(max_length=50)),
                ("customer_tax_id", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
