# Generated by Django 5.0.2 on 2024-03-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_alter_invoice_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="customer_phone",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
