# Generated by Django 5.0.2 on 2024-03-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0004_invoice_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="additional_information",
            field=models.TextField(blank=True),
        ),
    ]
