from django import forms
from .models import Invoice

FORM_CLASS = "w-full my-2 py-1 px-1 rounded-md bg-indigo-100"

class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        
        fields = [
            "place_of_creation",
            "date_of_creation",
            "date_of_service",
            "invoice_number",
            "currency",
            "method_payment",
            "service_type_1",
            "service_type_2",
            "service_type_3",
            "unit_1",
            "unit_2",
            "unit_3",
            "price_1",
            "price_2",
            "price_3",
            "amount_1",
            "amount_2",
            "amount_3",
            "additional_information",
            "company_name",
            "company_street_address",
            "company_city",
            "company_zip_code",
            "company_tax_id",
            "company_phone",
            "company_account_number",
            "customer_company_name",
            "customer_street_address",
            "customer_city",
            "customer_zip_code",
            "customer_tax_id",
            "customer_phone",
        ]
        
        labels = {
            "place_of_creation" : "Place Of Issue",
            "date_of_creation" : "Date Of Issue",
            "date_of_service" : "Date Of Service",
            "invoice_number" : "Invoice Number",
            "currency" : "Currency",
            "method_payment" : "Method Of Payment",
            "service_type_1" : "Name Of Sercive",
            "unit_1" : "Unit",
            "price_1" : "Price",
            "amount_1" : "Quantity",
            "company_name" : "Company Name",
            "company_street_address" : "Street Address",
            "company_city" : "City",
            "company_zip_code" : "Zip Code",
            "company_tax_id" : "Tax Id",
            "company_phone" : "Account Number",
            "company_account_number" : "Telephone Number",
            "customer_company_name" : "Company Name",
            "customer_street_address" : "Street Address",
            "customer_city" : "City",
            "customer_zip_code" : "Zip Code",
            "customer_tax_id" : "Tax Id",
            "customer" : "Telephone Number",
            "additional_information" : "Additional Information",
        }
        
        widgets = {
            "place_of_creation" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "date_of_creation" : forms.DateInput(attrs={"type" : "date", "class" : FORM_CLASS}),
            "date_of_service" : forms.DateInput(attrs={"type" : "date", "class" : FORM_CLASS}),
            "invoice_number" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "currency" : forms.Select(attrs={"class": FORM_CLASS}),
            "method_payment" :forms.Select(attrs={"class": FORM_CLASS}),
            "service_type_1" : forms.TextInput(attrs={"class" : FORM_CLASS, 'placeholder': "1"}),
            "service_type_2" : forms.TextInput(attrs={"class" : FORM_CLASS, 'placeholder': "2"}),
            "service_type_3" : forms.TextInput(attrs={"class" : FORM_CLASS, 'placeholder': "3"}),
            "unit_1" : forms.Select(attrs={"class": FORM_CLASS}),
            "unit_2" : forms.Select(attrs={"class": FORM_CLASS}),
            "unit_3" : forms.Select(attrs={"class": FORM_CLASS}),
            "price_1" : forms.NumberInput(attrs={"class": FORM_CLASS}),
            "price_2" : forms.NumberInput(attrs={"class": FORM_CLASS}),
            "price_3" : forms.NumberInput(attrs={"class": FORM_CLASS}),
            "amount_1" : forms.NumberInput(attrs={"class": FORM_CLASS}),
            "amount_2" : forms.NumberInput(attrs={"class": FORM_CLASS}),
            "amount_3": forms.NumberInput(attrs={"class": FORM_CLASS}),
            "additional_information": forms.Textarea(attrs={"class": FORM_CLASS, "rows": 1}),
            "company_name" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "company_street_address" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "company_city" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "company_zip_code" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "company_tax_id" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "company_phone" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "company_account_number" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "customer_company_name" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "customer_street_address" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "customer_city" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "customer_zip_code" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "customer_tax_id" : forms.TextInput(attrs={"class" : FORM_CLASS}),
            "customer_phone" : forms.TextInput(attrs={"class" : FORM_CLASS}),
        }